#!/usr/bin/env python3
"""Evaluate the complete low-data checkpoint grid with class-aware metrics.

Inference only: no model parameter is trained or modified. For fixed quantum
preprocessing, locally cached test tensors are reused when available; missing
seed caches are deterministically regenerated in memory from the exact Kaggle-
verified test images and the published fixed-circuit seed.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any

import numpy as np
import pennylane as qml
import torch
from torch.utils.data import DataLoader, TensorDataset

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.evaluate_classification_metrics import (  # noqa: E402
    aggregate_runs,
    class_names,
    confusion_matrix,
    evaluate_checkpoint,
    metric_text,
)
from src import config  # noqa: E402
from src.ablation_models import (  # noqa: E402
    ClassicalBaselineNet,
    NonTrainableQuantumClassicalNet,
)
from src.benchmark_protocol import load_raw_tensors, set_global_seed  # noqa: E402


SEEDS = list(range(42, 48))
FRACTIONS = (0.10, 0.25, 0.50, 1.00)


def fraction_tag(fraction: float) -> str:
    return f"{int(round(fraction * 100)):03d}"


def read_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def existing_quantum_test_cache(seed: int) -> tuple[torch.Tensor, torch.Tensor] | None:
    cache_root = ROOT / "experiments" / "quantum_cache"
    for metadata_path in sorted(cache_root.glob("*_metadata.json")):
        metadata = read_json(metadata_path)
        payload = metadata.get("cache_payload", {})
        shape = metadata.get("test_shape", [])
        if int(payload.get("seed", -1)) != seed or len(shape) < 2 or int(shape[1]) != 16:
            continue
        key = metadata["cache_key"]
        features = cache_root / f"{key}_test_features.npy"
        labels = cache_root / f"{key}_test_labels.npy"
        if features.exists() and labels.exists():
            return (
                torch.tensor(np.load(features), dtype=torch.float32),
                torch.tensor(np.load(labels), dtype=torch.long),
            )
    return None


def regenerate_fixed_quantum_test_features(
    images: torch.Tensor,
    seed: int,
    *,
    n_filters: int = 4,
    chunk_size: int = 4096,
) -> torch.Tensor:
    """Regenerate the exact Henderson-style test features with broadcasting."""
    image_array = images.squeeze(1).numpy()
    image_count = len(image_array)
    patches = (
        image_array.reshape(image_count, 16, 2, 16, 2)
        .transpose(0, 1, 3, 2, 4)
        .reshape(-1, 4)
        .astype(np.float64)
    )

    rng = np.random.RandomState(seed)
    filter_weights = [
        rng.uniform(-np.pi, np.pi, (4, 3)).astype(np.float64)
        for _ in range(n_filters)
    ]
    device = qml.device("default.qubit", wires=4)

    @qml.qnode(device, interface="numpy")
    def fixed_circuit(inputs: np.ndarray, weights: np.ndarray):
        qml.AngleEmbedding(inputs, wires=range(4))
        for qubit in range(4):
            qml.Rot(
                weights[qubit, 0],
                weights[qubit, 1],
                weights[qubit, 2],
                wires=qubit,
            )
        for qubit in range(3):
            qml.CNOT(wires=[qubit, qubit + 1])
        return [qml.expval(qml.PauliZ(qubit)) for qubit in range(4)]

    feature_groups: list[np.ndarray] = []
    for weights in filter_weights:
        chunks = [
            np.asarray(fixed_circuit(patches[start : start + chunk_size], weights), dtype=np.float32)
            for start in range(0, len(patches), chunk_size)
        ]
        output = np.concatenate(chunks, axis=1)
        output = output.reshape(4, image_count, 16, 16).transpose(1, 0, 2, 3)
        feature_groups.append(output)
    return torch.tensor(np.concatenate(feature_groups, axis=1), dtype=torch.float32)


def to_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Low-Data Class-Aware Classification Evidence",
        "",
        f"**Date:** {report['generated_date']}",
        "",
        "Generated by inference from the complete saved low-data checkpoint grid. No training was performed.",
        "All checkpoint accuracies matched their byte-original Drive JSON rows within the configured tolerance.",
        "",
        "## Six-Seed Test Metrics",
        "",
        "| Model | Train fraction | Runs | Accuracy | Macro-F1 | Balanced accuracy | Weighted-F1 |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in report["summary"]:
        lines.append(
            "| `{model}` | {fraction:.2f} | {runs} | {accuracy} | {macro_f1} | {balanced} | {weighted} |".format(
                model=row["model"],
                fraction=row["train_fraction"],
                runs=row["runs"],
                accuracy=metric_text(row, "accuracy"),
                macro_f1=metric_text(row, "macro_f1"),
                balanced=metric_text(row, "balanced_accuracy"),
                weighted=metric_text(row, "weighted_f1"),
            )
        )

    lines.extend(
        [
            "",
            "## Fixed-Quantum Minus Classical Differences",
            "",
            "| Train fraction | Accuracy difference (points) | Macro-F1 difference (points) |",
            "|---:|---:|---:|",
        ]
    )
    for row in report["paired_summary"]:
        lines.append(
            f"| {row['train_fraction']:.2f} | {row['accuracy_difference_mean']:+.2f} | "
            f"{row['macro_f1_difference_mean']:+.2f} |"
        )

    lines.extend(
        [
            "",
            "## Provenance",
            "",
            "- JSON rows are the byte-original Drive artifacts reconciled on 9 August 2026.",
            "- Seed-42 checkpoints were already local; seed 43--47 checkpoints came from the downloaded Drive folders.",
            "- Classical models use the fixed raw-image test split.",
            "- Fixed-quantum models use deterministic seed-specific test features; local caches were reused where available and otherwise regenerated in memory.",
            "- The companion JSON contains per-run confusion matrices and all 44 per-class metrics.",
            "",
            "These metrics strengthen class-aware reporting but do not change the exploratory status of the low-data comparison.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--accuracy-tolerance", type=float, default=0.03)
    parser.add_argument(
        "--json-out",
        default="experiments/low_data_classification_metrics_20260809.json",
    )
    parser.add_argument(
        "--md-out",
        default="docs/LOW_DATA_CLASSIFICATION_METRICS_2026-08-09.md",
    )
    args = parser.parse_args()

    _, _, raw_test_features, raw_test_labels = load_raw_tensors(config.IMAGE_SIZE)
    quantum_inputs: dict[int, tuple[torch.Tensor, torch.Tensor, str]] = {}
    run_rows: list[dict[str, Any]] = []

    for seed in SEEDS:
        cached = existing_quantum_test_cache(seed)
        if cached is not None:
            quantum_inputs[seed] = (*cached, "existing-local-cache")
        else:
            features = regenerate_fixed_quantum_test_features(raw_test_features, seed)
            quantum_inputs[seed] = (
                features,
                raw_test_labels,
                "deterministically-regenerated-in-memory",
            )

        for fraction in FRACTIONS:
            tag = fraction_tag(fraction)
            for model_name in ("classical_conv", "non_trainable_quantum"):
                set_global_seed(seed)
                result_path = ROOT / "experiments" / "low_data" / (
                    f"ablation_{model_name}_frac{tag}_seed{seed}_split42_fraction42.json"
                )
                checkpoint_path = ROOT / "models" / "low_data" / (
                    f"best_ablation_{model_name}_frac{tag}_seed{seed}_split42_fraction42.pth"
                )
                result = read_json(result_path)
                if model_name == "classical_conv":
                    builder = lambda: ClassicalBaselineNet(num_classes=config.NUM_CLASSES)
                    features, labels = raw_test_features, raw_test_labels
                    feature_source = "raw-kaggle-verified-test-images"
                else:
                    builder = lambda: NonTrainableQuantumClassicalNet(
                        in_channels=16, num_classes=config.NUM_CLASSES
                    )
                    features, labels, feature_source = quantum_inputs[seed]

                metrics, matrix = evaluate_checkpoint(
                    builder,
                    checkpoint_path,
                    features,
                    labels,
                    args.batch_size,
                    torch.device("cpu"),
                )
                expected_accuracy = float(result["test_acc"])
                if abs(metrics["accuracy"] - expected_accuracy) > args.accuracy_tolerance:
                    raise RuntimeError(
                        f"Accuracy mismatch for {model_name} fraction {fraction} seed {seed}: "
                        f"checkpoint={metrics['accuracy']}, JSON={expected_accuracy}"
                    )
                run_rows.append(
                    {
                        "family": "current-local",
                        "model": model_name,
                        "train_fraction": fraction,
                        "seed": seed,
                        "split_seed": 42,
                        "fraction_seed": 42,
                        "result_json": result_path.relative_to(ROOT).as_posix(),
                        "checkpoint": checkpoint_path.relative_to(ROOT).as_posix(),
                        "feature_source": feature_source,
                        "checkpoint_accuracy_verified_against_json": True,
                        **metrics,
                        "confusion_matrix": matrix.tolist(),
                    }
                )
                print(
                    f"Verified {model_name} fraction={fraction:.2f} seed={seed}: "
                    f"accuracy={metrics['accuracy']:.2f}, macro-F1={metrics['macro_f1']:.2f}"
                )

    grouped: dict[tuple[str, float], list[dict[str, Any]]] = defaultdict(list)
    for row in run_rows:
        grouped[(row["model"], float(row["train_fraction"]))].append(row)

    summary: list[dict[str, Any]] = []
    for (model_name, fraction), runs in sorted(grouped.items()):
        summary.append(
            {
                "family": "current-local",
                "model": model_name,
                "train_fraction": fraction,
                "runs": len(runs),
                "seeds": sorted(int(run["seed"]) for run in runs),
                **aggregate_runs(runs),
            }
        )

    paired_summary = []
    run_index = {
        (row["model"], float(row["train_fraction"]), int(row["seed"])): row
        for row in run_rows
    }
    for fraction in FRACTIONS:
        accuracy_differences = []
        macro_f1_differences = []
        for seed in SEEDS:
            classical = run_index[("classical_conv", fraction, seed)]
            quantum = run_index[("non_trainable_quantum", fraction, seed)]
            accuracy_differences.append(quantum["accuracy"] - classical["accuracy"])
            macro_f1_differences.append(quantum["macro_f1"] - classical["macro_f1"])
        paired_summary.append(
            {
                "train_fraction": fraction,
                "seeds": SEEDS,
                "accuracy_difference_quantum_minus_classical": accuracy_differences,
                "accuracy_difference_mean": round(float(np.mean(accuracy_differences)), 4),
                "macro_f1_difference_quantum_minus_classical": macro_f1_differences,
                "macro_f1_difference_mean": round(float(np.mean(macro_f1_differences)), 4),
            }
        )

    report = {
        "schema_version": 1,
        "generated_date": date.today().isoformat(),
        "operation": "checkpoint-inference-only",
        "training_performed": False,
        "provenance_manifest": "experiments/drive_artifact_reconciliation_20260809.json",
        "class_names": class_names(),
        "runs": run_rows,
        "summary": summary,
        "paired_summary": paired_summary,
    }
    json_out = ROOT / args.json_out
    md_out = ROOT / args.md_out
    json_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    md_out.write_text(to_markdown(report), encoding="utf-8")
    print(f"Wrote {json_out.relative_to(ROOT)}")
    print(f"Wrote {md_out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
